export const SERVICE_WATERMARK = Symbol('__SERVICE__');
export const TRANSACTIONAL_WATERMARK = Symbol('__TRANSACTIONAL__');
export const TRANSACTIONAL_OPTIONS = Symbol('__TRANSACTIONAL_OPTIONS__');
export const TRANSACTIONAL_EVENT_COMMITTED = 'TRANSACTIONAL_EVENT_COMMITTED';
